version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/action/
    overwrite: yes

permissions:
  - object: /home/ec2-user
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/prod-deploy.sh
      timeout: 300
      runas: ec2-user