package team.msg.domain.lecture.exception.constant

enum class LectureErrorCode(
    val status: Int
){
    INVALID_LECTURE_TYPE(400),

    FORBIDDEN_SIGNED_UP_LECTURE(403),

    LECTURE_NOT_FOUND(404),
    REGISTERED_LECTURE_COUNT_NOT_FOUND(404),

    ALREADY_APPROVED_LECTURE(409),
    ALREADY_SIGNED_UP_LECTURE(409),
    UNAPPROVED_LECTURE(409),
    UNSIGNED_UP_LECTURE(409),
    OVER_MAX_REGISTERED_USER(409),
    NOT_AVAILABLE_SIGN_UP_DATE(409)
}
